### ISSUE TITLE
ValueError: Shape must be rank 2 but is rank 3 for 'bert/embeddings/MatMul' (op: 'MatMul') with input shapes: [?,?,16], [16,32].

### ISSUE THREAD

**Issue by Shanzaay** [KnightZhang625/BERT_TF#2]
Hi. While i execute the pre-train.py file. I am getting the following error. 

ValueError: Shape must be rank 2 but is rank 3 for 'bert/embeddings/MatMul' (op: 'MatMul') with input shapes: [?,?,16], [16,32].

Can anyone guide me on how to remove it.

**Comment by KnightZhang625** [comment]
Hi, there. Please show me that your input data like, what is your embedding size, and what is your sequence length, and your vocab size. Thanks.

**Comment by Shanzaay** [comment]
The error is occurring on mdel_helper.py  on line 151 while executing the  pre_train.py file. And I am using the default code. I haven't made any changes to it. So it's the same that the code already contains.

**Comment by Shanzaay** [comment]
Am i suppose to give path value here: PROJECT_PATH = Path(__file__).absolute().parent

**Comment by KnightZhang625** [comment]
The project path will be generate automatically, there's no need for you to specify it. I am trying to find the bug, the repository is a little mess due to mix of two problems.

**Comment by KnightZhang625** [comment]
for 151th line, please change 'embeddings' to tf.reshape(embeddings, shape=[-1, embedding_size]), which will make the embedding to the shape of (batch_size * seq_length, embedding_size), then use 'tf.matmul(embeddings, project_variable)', the output will be the shape of (batch_size * seq_length, hidden_size), finally, reshape the output by tf.reshape(output, (-1, seq_length, hidden_size)).

**Comment by Shanzaay** [comment]
Thanks a lot for your response. But it seems like seq_length is undefined.  Is it alright to define it like this:
batch_size, seq_length, width = input_shape[0], input_shape[1], input_shape[2]

As It is defined like this in **embedding_postprocessor** function.

**Comment by Shanzaay** [comment]
> for 151th line, please change 'embeddings' to tf.reshape(embeddings, shape=[-1, embedding_size]), which will make the embedding to the shape of (batch_size * seq_length, embedding_size), then use 'tf.matmul(embeddings, project_variable)', the output will be the shape of (batch_size * seq_length, hidden_size), finally, reshape the output by tf.reshape(output, (-1, seq_length, hidden_size)).

But then i have to define so many other things. Can you please let me know how to define seq_length here?

**Comment by KnightZhang625** [comment]
Please try 'get_shape_list' function in model_helper.py to get the dynamic tensor shape, there's no need for you to get the exact shape.  Like, 
"""
input_shape = get_shape_list(input_tensor, expected_rank=3)
  batch_size = input_shape[0]
  seq_length = input_shape[1]
  width = input_shape[2]

"""

**Comment by KnightZhang625** [comment]
Please try this method first, if it doesn't work, you could reshape the 'input_ids' to one dimension like, flat_input_ids = tf.reshape(input_ids, [-1]), this will make 'input_ids' to (batch_size * sequence_length, ),  then use 'one_hot_input_ids = tf.one_hot(flat_input_ids,depth=vocab_size)' to make the 'input_ids' to (batch_size * sequence_length, vocal_size), then use tf.matmul or tf.nn.embedding_lookup() to get the first embedding, the shape should be (batch_size * sequence_length, embedding_size), then the 'MatMul' operation will execute correctly.

**Comment by Shanzaay** [comment]
input_shape = get_shape_list(input_tensor, expected_rank=[2,3])

Now, input_tensor is undefined.

**Comment by Shanzaay** [comment]
> Please try this method first, if it doesn't work, you could reshape the 'input_ids' to one dimension like, flat_input_ids = tf.reshape(input_ids, [-1]), this will make 'input_ids' to (batch_size * sequence_length, ), then use 'one_hot_input_ids = tf.one_hot(flat_input_ids,depth=vocab_size)' to make the 'input_ids' to (batch_size * sequence_length, vocal_size), then use tf.matmul or tf.nn.embedding_lookup() to get the first embedding, the shape should be (batch_size * sequence_length, embedding_size), then the 'MatMul' operation will execute correctly.

So if try this method should i not use this function : **input_shape = get_shape_list(input_tensor, expected_rank=[2,3])**  ?

**Comment by KnightZhang625** [comment]
input_tensor should be input_ids as defined in Formal Parameter of embedding_lookup_factorized function.

**Comment by Shanzaay** [comment]
Oky so i add these line in model_helper file in function embedding_lookup_factorized. 
     **flat_input_ids = tf.reshape(input_ids, [-1])
    one_hot_input_ids = tf.one_hot(flat_input_ids,depth=vocab_size)
    input_shape = get_shape_list(one_hot_input_ids, expected_rank=[2,3])  
    batch_size, seq_length, width = input_shape[0], input_shape[1], input_shape[2]** 

Now i am getting the following error: 
  File "F:\BERT_TF-master\model_helper.py", line 135, in embedding_lookup_factorized
    batch_size, seq_length, width = input_shape[0], input_shape[1], input_shape[2]  

IndexError: list index out of range

**Comment by KnightZhang625** [comment]
what I mean is that, do 'input_shape = get_shape_list(one_hot_input_ids, expected_rank=[2,3])' this step after embedding, then the tensor should be 3 dimensions, IndexError is because of one_hot_input_ids is only 2 dimension.
