### ISSUE TITLE
pre_train.py L201 is wrong

### ISSUE THREAD

**Issue by deepthinking-qichao** [KnightZhang625/BERT_TF#3]
label_weights = tf.cast(tf.reshape(label_ids, [-1]), dtype=tf.float32) should rewrite to 
label_weights = tf.cast(tf.reshape(label_weights , [-1]), dtype=tf.float32)

**Comment by KnightZhang625** [comment]
True, I checked the original code, this code is identical to the original google bert code, just more comments. Thanks !

**Comment by KnightZhang625** [comment]
The code in 201th line is wrong, just to reaffirm.
